package ai

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nuzur/go-code-gen/project"
	nemgen "github.com/nuzur/nem/idl/gen"
)

// aiSchema is a minimal schema with one standalone entity, enough for the
// guidance to render concrete examples.
func aiSchema() *nemgen.ProjectVersion {
	return &nemgen.ProjectVersion{
		Entities: []*nemgen.Entity{
			{
				Uuid:       "c1682705-1a89-4cc1-9b1f-e9a888c00000",
				Identifier: "user",
				Type:       nemgen.EntityType_ENTITY_TYPE_STANDALONE,
				Fields: []*nemgen.Field{
					{
						Uuid:       "d1682705-1a89-4cc1-9b1f-e9a888c00001",
						Identifier: "id",
						Type:       nemgen.FieldType_FIELD_TYPE_UUID,
						Key:        true,
						Required:   true,
						Status:     nemgen.FieldStatus_FIELD_STATUS_ACTIVE,
						TypeConfig: &nemgen.FieldTypeConfig{},
					},
				},
				TypeConfig: &nemgen.EntityTypeConfig{
					Standalone: &nemgen.EntityTypeStandaloneConfig{},
				},
			},
		},
	}
}

func generateAIMarkdown(t *testing.T, mutate func(p *project.ProjectParams)) string {
	t.Helper()

	root := t.TempDir()
	params := &project.ProjectParams{
		Project:        &nemgen.Project{Name: "AI Guidance"},
		ProjectVersion: aiSchema(),
		RootPath:       root,
		Identifier:     "aidocs",
		Module:         "github.com/mklfarha/aidocs",
		EntitiesConfig: project.EntitiesConfig{Enabled: true, Dir: "entity"},
		CoreConfig: project.CoreConfig{
			Enabled:    true,
			CoreDir:    "core",
			RepoConfig: project.RepoConfig{DatabaseType: project.MYSQL},
		},
	}
	if mutate != nil {
		mutate(params)
	}

	if err := GenerateAIInfo(context.Background(), params); err != nil {
		t.Fatalf("GenerateAIInfo failed: %v", err)
	}

	b, err := os.ReadFile(filepath.Join(root, params.Identifier, "AI.md"))
	if err != nil {
		t.Fatalf("reading AI.md: %v", err)
	}
	return string(b)
}

// TestGenerateAIInfoCustomEnabled covers the guidance an agent needs to add
// custom endpoints: the user-owned zone, both transports and the data layer.
func TestGenerateAIInfoCustomEnabled(t *testing.T) {
	out := generateAIMarkdown(t, func(p *project.ProjectParams) {
		p.ProtoConfig = project.ProtoConfig{Enabled: true, Server: true, Dir: "idl"}
		p.RESTConfig = project.RESTConfig{Enabled: true, OpenAPI: true, SwaggerUI: true}
		p.CustomConfig = project.CustomConfig{Enabled: true, Dir: "app"}
		p.StorageConfig = project.StorageConfig{Enabled: true}
		p.AuthConfig = project.AuthConfig{Enabled: true, Type: project.KEYCLOAK_AUTH_TYPE}
	})

	for _, want := range []string{
		"Code generated by nuzur go-code-gen. DO NOT EDIT.",
		".nuzur-codegen-manifest.json",
		"Custom Application Zone — `app/`",
		"app/rest.go",
		"app/idl/proto/custom.proto",
		"pb.AidocsServer",
		"CreateUser(ctx context.Context, req *pb.CreateUserRequest) (*pb.User, error)",
		"coreImpl.User().List(",
		"POST /upload",
		"GET /` — the info page",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("AI.md missing %q\n---\n%s", want, out)
		}
	}
}

// TestGenerateAIInfoCustomDisabled verifies the guidance tells an agent there is
// no user-owned zone (and how to get one) rather than describing a directory
// that was never generated.
func TestGenerateAIInfoCustomDisabled(t *testing.T) {
	out := generateAIMarkdown(t, nil)

	if !strings.Contains(out, "custom application zone is disabled") {
		t.Errorf("AI.md should state the custom zone is disabled\n---\n%s", out)
	}
	if strings.Contains(out, "Custom Application Zone —") {
		t.Errorf("AI.md should not document the custom zone when disabled\n---\n%s", out)
	}
	if !strings.Contains(out, "**Custom Application Zone**: `Disabled`") {
		t.Errorf("AI.md specs should report the custom zone as disabled\n---\n%s", out)
	}
}
