package files

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path"
	"strings"
	"text/template"

	"github.com/nuzur/filetools"
)

// GeneratedMarker is the stable sentence embedded as a comment in every file the
// generator writes. It intentionally follows the Go "Code generated ... DO NOT
// EDIT." convention so that, for Go files, the standard tooling regexp
// (`^// Code generated .* DO NOT EDIT\.$`) also recognizes them.
//
// Tooling (e.g. the CLI's stale-file cleanup) can treat any file containing this
// marker as generated, and therefore safe to delete when it is no longer
// produced — while leaving files the user added (which never carry the marker)
// untouched.
const GeneratedMarker = "Code generated by nuzur go-code-gen. DO NOT EDIT."

// GenerateFile wraps filetools.GenerateFile, injecting GeneratedMarker as a
// comment appropriate to the output file type. It is a drop-in replacement for
// filetools.GenerateFile across the generator.
func GenerateFile(ctx context.Context, req filetools.FileRequest) ([]byte, error) {
	notice := generatedNotice(req.OutputPath)
	if notice != "" {
		tmpl := req.TemplateBytes
		if tmpl == nil && req.TemplatePath != "" {
			b, err := os.ReadFile(req.TemplatePath)
			if err != nil {
				return nil, err
			}
			tmpl = b
		}
		if tmpl != nil {
			req.TemplateBytes = injectNotice(tmpl, notice)
			req.TemplatePath = ""
		}
	}
	return filetools.GenerateFile(ctx, req)
}

// GenerateFileWithDelims is GenerateFile for templates whose OUTPUT is itself a
// Go-templated file — Helm charts, most notably. Rendered with the default
// delimiters, every literal Helm action in such a template has to be written as
// {{ "{{" }} ... {{ "}}" }}, which is unreadable and easy to get wrong. With
// left/right set to << >>, the generator's own substitutions are << >> and
// Helm's {{ }} passes through untouched.
//
// filetools.GenerateFile hardcodes the default delimiters, so this reimplements
// its (small) render-and-write loop rather than wrapping it. Go formatting is
// deliberately not applied: these outputs are never Go source.
func GenerateFileWithDelims(ctx context.Context, req filetools.FileRequest, left, right string) ([]byte, error) {
	tmplBytes := req.TemplateBytes
	if tmplBytes == nil && req.TemplatePath != "" {
		b, err := os.ReadFile(req.TemplatePath)
		if err != nil {
			return nil, err
		}
		tmplBytes = b
	}
	if notice := generatedNotice(req.OutputPath); notice != "" && tmplBytes != nil {
		tmplBytes = injectNotice(tmplBytes, notice)
	}

	funcs := template.FuncMap{}
	for n, f := range req.Funcs {
		funcs[n] = f
	}

	t, err := template.New("template").Delims(left, right).Funcs(funcs).Parse(string(tmplBytes))
	if err != nil {
		return nil, fmt.Errorf("error parsing template for %s: %w", req.OutputPath, err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, req.Data); err != nil {
		return nil, fmt.Errorf("error executing template for %s: %w", req.OutputPath, err)
	}

	out := buf.Bytes()
	if err := filetools.Write(req.OutputPath, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MarkGeneratedFile prepends the generated-file marker (in the comment style of
// the file type) to an already-written file. Use it for outputs not produced
// through GenerateFile, e.g. files copied in from another tool. It is a no-op
// for types that cannot carry a comment, or if the file is already marked.
func MarkGeneratedFile(filePath string) error {
	notice := generatedNotice(filePath)
	if notice == "" {
		return nil
	}
	b, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	head := b
	if len(head) > 512 {
		head = head[:512]
	}
	if strings.Contains(string(head), GeneratedMarker) {
		return nil
	}
	return os.WriteFile(filePath, injectNotice(b, notice), 0644)
}

// IsGenerated reports whether the file at the given path was produced by code
// generation. It recognizes both this generator's marker and the standard Go
// "Code generated ... DO NOT EDIT." convention used by tools we invoke (sqlc,
// protoc), so tool outputs are detected too. Files added by the user carry no
// such marker and therefore return false.
func IsGenerated(filePath string) bool {
	f, err := os.Open(filePath)
	if err != nil {
		return false
	}
	defer f.Close()
	// The marker is always near the top; reading the first 512 bytes is enough.
	buf := make([]byte, 512)
	n, _ := f.Read(buf)
	return hasGeneratedMarker(string(buf[:n]))
}

// hasGeneratedMarker reports whether head contains a generated-file marker, in
// any comment style, from this generator or a tool following the Go convention.
func hasGeneratedMarker(head string) bool {
	return strings.Contains(head, "Code generated") && strings.Contains(head, "DO NOT EDIT")
}

// generatedNotice returns the marker wrapped in the comment syntax for the
// output file type, including trailing blank lines, or "" when the type cannot
// safely carry a comment (in which case no marker is injected).
func generatedNotice(outputPath string) string {
	name := path.Base(outputPath)
	ext := strings.ToLower(path.Ext(outputPath))
	switch {
	case ext == ".go" || ext == ".proto":
		return "// " + GeneratedMarker + "\n\n"
	case ext == ".md":
		return "<!-- " + GeneratedMarker + " -->\n\n"
	case ext == ".sql":
		return "-- " + GeneratedMarker + "\n"
	case ext == ".yaml" || ext == ".yml" || ext == ".sh" || ext == ".toml" || name == "Dockerfile":
		return "# " + GeneratedMarker + "\n"
	// Helm partials (_helpers.tpl). Without this they carry no marker, so
	// scanGeneratedFiles never lists them, stale-cleanup can never remove them,
	// and they read as user-authored. Helm discards the rendered output of
	// _-prefixed files, so a leading comment line is inert.
	case ext == ".tpl":
		return "# " + GeneratedMarker + "\n"
	default:
		return ""
	}
}

// injectNotice places the notice at the top of the template, but after a
// shebang line if one is present (so executable scripts keep `#!` first).
func injectNotice(tmpl []byte, notice string) []byte {
	s := string(tmpl)
	if strings.HasPrefix(s, "#!") {
		if idx := strings.IndexByte(s, '\n'); idx != -1 {
			return []byte(s[:idx+1] + notice + s[idx+1:])
		}
	}
	return []byte(notice + s)
}
